/**
 * GoDeploy MCP shim — version marker: godeploy-mcp-shim@1
 *
 * DO NOT EDIT THIS FILE. It is copied verbatim into every app that exposes an
 * MCP interface at `/_mcp`. Editing or regenerating it risks module-evaluation
 * failures that surface as a generic 502 with empty logs — undebuggable from
 * the app side. The version marker above (also embedded as the `SHIM_VERSION`
 * constant below) is how the platform detects the shim in deployed bundles;
 * keep both intact.
 *
 * Design constraints (why this file looks the way it does):
 * - Zero value imports — only types from `./define`. Any npm import re-enters
 *   the bundler-interop risk class that breaks the MCP SDK in apps.
 * - No top-level statement can throw: module scope is constants and arrow
 *   functions only. All validation happens at request time and surfaces as
 *   JSON-RPC errors.
 * - Stateless: no sessions, no SSE, no module-level mutable state. A
 *   `Mcp-Session-Id` header is ignored if sent and never issued.
 */
import type { McpManifest, McpTool, ToolContext } from "./define";

const SHIM_VERSION = "godeploy-mcp-shim@1";

// Protocol revisions this shim's JSON-RPC subset is known-compatible with.
const SUPPORTED_PROTOCOL_VERSIONS = ["2025-06-18", "2025-03-26"];
const DEFAULT_PROTOCOL_VERSION = "2025-06-18";

// tools/list has no pagination, so the manifest is capped instead.
const MAX_TOOLS = 64;
const TOOL_NAME_RE = /^[a-zA-Z0-9_-]{1,64}$/;

// JSON-RPC 2.0 error codes.
const PARSE_ERROR = -32700;
const INVALID_REQUEST = -32600;
const METHOD_NOT_FOUND = -32601;
const INVALID_PARAMS = -32602;

type JsonRpcId = string | number | null;

const isRecord = (v: unknown): v is Record<string, unknown> =>
  typeof v === "object" && v !== null && !Array.isArray(v);

const jsonResponse = (body: unknown, status = 200): Response =>
  new Response(JSON.stringify(body), {
    status,
    headers: { "Content-Type": "application/json" },
  });

const rpcResult = (id: JsonRpcId, result: unknown): Response =>
  jsonResponse({ jsonrpc: "2.0", id, result });

const rpcError = (id: JsonRpcId, code: number, message: string): Response =>
  jsonResponse({ jsonrpc: "2.0", id, error: { code, message } });

// Manifest entries are validated here (not at module eval) so an authoring
// mistake degrades to a JSON-RPC error instead of a module-eval 502.
const toolError = (tool: McpTool): string | null => {
  if (!isRecord(tool)) return "tool is not an object";
  if (typeof tool.name !== "string" || !TOOL_NAME_RE.test(tool.name)) {
    return `tool name must match ${TOOL_NAME_RE.source}`;
  }
  if (typeof tool.description !== "string") return `tool "${tool.name}" is missing a description`;
  if (!isRecord(tool.inputSchema)) return `tool "${tool.name}" inputSchema must be a JSON Schema object`;
  if (typeof tool.handler !== "function") return `tool "${tool.name}" handler must be a function`;
  return null;
};

// Only the first MAX_TOOLS entries exist as far as the protocol is concerned —
// keeps tools/list and tools/call consistent with each other.
const manifestTools = (manifest: McpManifest): McpTool[] =>
  Array.isArray(manifest?.tools) ? manifest.tools.slice(0, MAX_TOOLS) : [];

const toToolResult = (value: unknown): Record<string, unknown> => {
  if (typeof value === "string") {
    return { content: [{ type: "text", text: value }] };
  }
  // `JSON.stringify` is undefined for undefined — fall back to "null" so the
  // text content is always a string.
  const text = JSON.stringify(value) ?? "null";
  // structuredContent is a JSON *object* in the MCP schema (SDK clients
  // validate it as such) — attach it only for plain objects.
  return isRecord(value)
    ? { content: [{ type: "text", text }], structuredContent: value }
    : { content: [{ type: "text", text }] };
};

const handleInitialize = (id: JsonRpcId, params: Record<string, unknown> | undefined, manifest: McpManifest): Response => {
  const requested = typeof params?.protocolVersion === "string" ? params.protocolVersion : "";
  const protocolVersion = SUPPORTED_PROTOCOL_VERSIONS.includes(requested)
    ? requested
    : DEFAULT_PROTOCOL_VERSION;
  return rpcResult(id, {
    protocolVersion,
    capabilities: { tools: {} },
    serverInfo: {
      name: manifest?.name ?? "godeploy-app",
      version: `${manifest?.version ?? "0.0.0"} (${SHIM_VERSION})`,
    },
  });
};

const handleToolsList = (id: JsonRpcId, manifest: McpManifest): Response => {
  const tools = manifestTools(manifest);
  for (const tool of tools) {
    const error = toolError(tool);
    if (error !== null) return rpcError(id, INVALID_PARAMS, `Invalid manifest entry: ${error}`);
  }
  return rpcResult(id, {
    tools: tools.map((t) => ({
      name: t.name,
      description: t.description,
      inputSchema: t.inputSchema,
    })),
  });
};

const handleToolsCall = async (
  id: JsonRpcId,
  params: Record<string, unknown> | undefined,
  env: Record<string, unknown>,
  request: Request,
  manifest: McpManifest,
): Promise<Response> => {
  const name = typeof params?.name === "string" ? params.name : "";
  if (!TOOL_NAME_RE.test(name)) {
    return rpcError(id, INVALID_PARAMS, `Tool name must match ${TOOL_NAME_RE.source}`);
  }
  const tool = manifestTools(manifest).find((t) => isRecord(t) && t.name === name);
  if (!tool) return rpcError(id, INVALID_PARAMS, `Unknown tool: ${name}`);
  const entryError = toolError(tool);
  if (entryError !== null) return rpcError(id, INVALID_PARAMS, `Invalid manifest entry: ${entryError}`);

  const args = params?.arguments === undefined ? {} : params.arguments;
  if (!isRecord(args)) return rpcError(id, INVALID_PARAMS, "params.arguments must be an object");

  const ctx: ToolContext = {
    env,
    userEmail: request.headers.get("X-Godeploy-User-Email"),
    request,
  };
  // Handler failures (including unserializable results) are tool results with
  // isError, never an HTTP 5xx — a 5xx here would mask the real error behind
  // the gateway's generic "App error".
  try {
    return rpcResult(id, toToolResult(await tool.handler(args, ctx)));
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    return rpcResult(id, { isError: true, content: [{ type: "text", text: message }] });
  }
};

export const handleMcp = async (
  request: Request,
  env: Record<string, unknown>,
  manifest: McpManifest,
): Promise<Response> => {
  // No SSE stream to GET, no session to DELETE — POST is the whole surface.
  if (request.method !== "POST") {
    return new Response(null, { status: 405, headers: { Allow: "POST" } });
  }

  let message: unknown;
  try {
    message = await request.json();
  } catch {
    return rpcError(null, PARSE_ERROR, "Parse error: body is not valid JSON");
  }

  if (Array.isArray(message)) {
    return rpcError(null, INVALID_REQUEST, "JSON-RPC batching is not supported");
  }
  if (!isRecord(message) || message.jsonrpc !== "2.0" || typeof message.method !== "string") {
    return rpcError(null, INVALID_REQUEST, "Invalid JSON-RPC request");
  }

  // A message without an id is a notification (e.g. notifications/initialized);
  // JSON-RPC forbids responding to those, so every notification gets 202.
  if (!("id" in message) || message.id === undefined) {
    return new Response(null, { status: 202 });
  }
  const id: JsonRpcId =
    typeof message.id === "string" || typeof message.id === "number" ? message.id : null;
  const params = isRecord(message.params) ? message.params : undefined;

  switch (message.method) {
    case "initialize":
      return handleInitialize(id, params, manifest);
    case "ping":
      return rpcResult(id, {});
    case "tools/list":
      return handleToolsList(id, manifest);
    case "tools/call":
      return handleToolsCall(id, params, env, request, manifest);
    default:
      return rpcError(id, METHOD_NOT_FOUND, `Method not found: ${message.method}`);
  }
};
